use_frameworks!

source "https://github.com/CocoaPods/Specs.git"
platform :ios, '10.0'

target 'FAService' do
  pod 'SnapKit', '~> 5.6.0'
  
  pod 'FastAppService', :path => '../'
  pod 'FastExtension', :path => "../../FastExtension"
end
